services:
  web:
    container_name: web_capstone
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn capstone_directory_api.wsgi:application --bind 0.0.0.0:8000 --timeout 30 --workers 2 # --reload  
    ports:
      - 8000:8000
    environment:
      - .env
      - CONTAINER_NAME=web
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
      - ./app/:/usr/src/app/
    depends_on:
      - postgres
    expose:
      - 8000

  postgres:
    container_name: postgres_capstone
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - capstone_directory_api_local_postgres_data:/var/lib/postgresql/data
      - capstone_directory_api_local_postgres_data_backups:/backups
    environment:
      - ./app/.env
    restart: always
    expose:
      - 5432
    
  redis:
    container_name: redis_capstone
    image: redis:7-alpine
    restart: always

  celery_worker:
    container_name: celery_worker_1
    build:
      context: ./app
      dockerfile: Dockerfile
    command: celery -A capstone_directory_api worker -l info
    volumes:
      - .:/app
    environment:
      - ./app/.env
    restart: always 
    depends_on:
      - redis
      - postgres
      - web

  celery_beat:
    container_name: celery_beat_1
    build:
      context: ./app
      dockerfile: Dockerfile
    command: celery -A capstone_directory_api beat -l info
    volumes:
      - .:/app
    environment:
      - ./app/.env
    restart: always
    depends_on:
      - redis
      - postgres
      - web

volumes:
  static_volume:
  media_volume:
  capstone_directory_api_local_postgres_data: {}
  capstone_directory_api_local_postgres_data_backups: {}