# Generated by Django 5.1.3 on 2024-11-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_capstonegroups_course_capstonegroups_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='student_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
