# Generated by Django 5.1.3 on 2024-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
