# Generated by Django 5.1.3 on 2024-11-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capstonegroups',
            old_name='number',
            new_name='name',
        ),
    ]
