# Generated by Django 5.1.3 on 2024-11-27 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_number_capstonegroups_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_members', to='users.capstonegroups'),
        ),
    ]
