# Generated by Django 5.1.3 on 2024-12-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstoneprojects',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
