# Generated by Django 5.1.3 on 2024-12-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_projects', '0002_alter_capstoneprojects_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstoneprojects',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
