# Generated by Django 5.1.3 on 2024-12-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_projects', '0005_capstoneprojects_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstoneprojects',
            name='is_approved',
            field=models.CharField(default='pending'),
        ),
    ]
